# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(verbose_name='Інформація')),
                ('image', models.ImageField(default=None, upload_to='images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Інформація про компанію',
            },
        ),
        migrations.CreateModel(
            name='DepartmentsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('0', 'Київська'), ('1', 'АР Крим'), ('2', 'Вінницька'), ('3', 'Волинська'), ('4', 'Дніпровська'), ('5', 'Донецька'), ('6', 'Житомирська'), ('7', 'Закарпатська'), ('8', 'Запорізька'), ('9', 'Івано-Франківська'), ('10', 'Кіровоградська'), ('11', 'Луганська'), ('12', 'Львівська'), ('13', 'Миколаївська'), ('14', 'Одеська'), ('15', 'Полтавська'), ('16', 'Рівненська'), ('17', 'Сумська'), ('18', 'Тернопільська'), ('19', 'Харківська'), ('20', 'Херсонська'), ('21', 'Хмельницька'), ('22', 'Черкаська'), ('23', 'Чернівецька'), ('24', 'Чернігівська')], max_length=2, verbose_name='Область')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('address', models.CharField(max_length=255, verbose_name='Вулиця, будинок')),
                ('photo', models.ImageField(default=None, upload_to='images', verbose_name='Зображення відділення')),
            ],
            options={
                'verbose_name_plural': 'Філіали',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Опис новини')),
                ('date', models.DateField(default=datetime.date(2017, 10, 23), verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва послуги')),
                ('description', models.TextField(verbose_name='Опис послуги')),
                ('image', models.ImageField(default=None, upload_to='images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
