# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Strahova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 24, 9, 24, 43, 149351, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
