# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strahova', '0002_auto_20171024_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
