# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strahova', '0004_auto_20171121_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
